### PR TITLE
Improve performance of writing JsonObject and JsonArray

### PR DESCRIPTION
**Pull request by matrixx567**
Hello Ralf,

I improved the performance of writing JsonObjects and JsonArray a little bit. Therefore I handle the first element of the array before the loop and this allows to remove the IF statement within the WHILE-loop.

BR Martin

### CODE REVIEW

**Comment by mafagafogigante** [comment]
Spacing is inconsistent (compare 459 and 462).

There is no benchmarking, just a promise. After fixing the spacing, the change seems worth merging, as I would also say that this is the right way of doing it. But at least a microbenchmarking is expected if you are going to claim a performance improvement.

**Comment by sbandara** [comment]
Interesting! Did you get a chance to measure how much this increases throughput?

**Comment by matrixx567** [comment]
I executed the benchmarks on my machine this morning and here are the results:

minimal-json-benchmark1
minimal-json-benchmark2
minimal-json-benchmark3

**Comment by matrixx567** [comment]
Another slight improvement to the original code of the Array's and Object's write method is to put the `first=false;` statement into the IF statement. So it will be only called once for the loop.

**Comment by mafagafogigante** [comment]
> Another slight improvement to the original code of the Array's and Object's write method is to put the first=false; statement into the IF statement.

@matrixx567 Sorry, do we even need it? What you proposed for `void write(JsonWriter)` seems better.

**Comment by ralfstx** [comment]
Thanks for the change @matrixx567! Performance aside, the code is clearer and better.

Fixed the formatting in https://github.com/ralfstx/minimal-json/commit/0ff90d9a73630495f26522aa81e047004362c73c

**Comment by mafagafogigante** [comment]
> Performance aside, the code is clearer and better.

I agree.

> Fixed the formatting in https://github.com/ralfstx/minimal-json/commit/0ff90d9a73630495f26522aa81e047004362c73c

Thank you for also caring about this.

**Pull request merged**
