### PR TITLE
Adds JsonObject#contains

### PR DESCRIPTION
**Pull request by WalkerKnapp**
I was moving over to this API from Jackson, and couldn't find a method for checking the presence of a member of an object. I know that you can always check if a value is null, but I would love something more concise.

### CODE REVIEW

**Comment by WalkerKnapp** [comment]
Just wondering, is there a reason why this was not originally included while it is in almost every other Json API?

**Comment by ralfstx** [comment]
Thanks @WalkerKnapp! Looks good to me. I want to keep the API minimal, but this one method is fair enough. Would you mind adding a test or two to `JsonObject_Test`?

**Comment by WalkerKnapp** [comment]
Sure! Thank you!

**Comment by ralfstx** [comment]
Thank you!

**Pull request merged**
