### PR TITLE
A hybrid streaming API.

### PR DESCRIPTION
**Pull request by sbandara**
Hi Ralf,

To address the feature request you posted and my own need for a streaming API, I created a branch "streams" and added a <code>CollectionFactory</code> interface to provide <code>JsonParser</code> with new instances of <code>JsonObject</code>,<code>JsonArray</code>, or custom implementations of an <code>ElementReader</code> or <code>MemberReader</code>, respectively.

A client implementation of <code>CollectionFactory</code> may choose to return a custom <code>ElementReader</code> or <code>MemberReader</code>, depending on nesting level and/or field name of the most recent ancestor object. Those implementations will receive children JsonValue objects from the parser and can choose to filter them or otherwise extract content. Effectively, those minor changes would provide minimal-json with a streaming API, allowing clients to reduce their memory footprint.

The abstract factory methods so far only receive the nesting level and the field name of the closest ancestor, but we could also add line number and column offset to allow Angelo implement a schema reader. Let me know what you think...

Adding those extensions, by the way, was very straightforward due to very clean design of your parser. Thank you so much for making minimal-json available for everyone!

Best wishes,
Sam

### CODE REVIEW

**Comment by sbandara** [comment]
Just pushed the alternative commit 72a588e, in which <code>JsonParser</code> works without a default factory -- maybe this is preferred style.

**Comment by ralfstx** [comment]
Hi Sam,

thanks for sharing your work! Streaming support is one of the next topic on my wishlist as well, I've already drafted some ideas some time ago and now I'm curious how you did it. I'm on vacation right now so it might be a week or so before I can look into your changes closely - but I definitely will come back to you then.

Thank you!
Ralf

**Comment by sbandara** [comment]
Sounds great! With the most recent commit, there are three tested "patterns" for how one could use a custom <code>CollectionFactory</code> that returns implementations of <code>ElementReader</code> and <code>MemberReader</code>:
* Mix-in custom array or object representations depending on context (e.g. based on nesting level or member name) that filter or extract from nested content, see bus route test case since 1184844.
* Return "builders" that construct or modify separate data structures from extracted content or context features such as stream position (see editor test case since e33517d).
* Commit aa4aaab would also allow mixing in of standard full-fledged but subclassed <code>JsonArray</code>s or <code>JsonObject</code>s where the <code>protected</code> <code>addElement</code> or <code>addMember</code> have overrides for filtering.

The changes would allow users of minimal-json to parse infinitely long streams, but to reduce object churn I am also wondering if <code>ParserContext</code> should provide <code>skip</code> methods that would allow us to skip the next *n* array elements or to break out of the array or object entirely... Enjoy your vacation!

**Comment by sbandara** [comment]
Here some added functionality for skipping stream content:
* One element, *n* elements, or all elements can be skipped from the current array, by invoking <code>skipNext()</code>, <code>skipNext(n)</code>, or <code>skipAll()</code> on the <code>ParserContext</code> exposed in <code>createElementReader</code> or <code>addElement</code>.
* <code>skipAll()</code> analogously can be used for skipping all remaining members of the current object, e.g. when all relevant members have been read. However, because members should be assumed unordered, invoking <code>skipNext()</code> or <code>skipNext(n)</code> from inside <code>createMemberReader</code> or <code>addMember</code> throws an <code>IllegalStateException</code>.
* Entire arrays and objects - not only their content - can be skipped by returning <code>null</code> from the corresponding factory method depending on context properties. This means that the member or element of the *enclosing* collection is skipped.

I don't think I should make more amendments. Looking forward to hear what you think. With the most recent changes there should be clear savings in object allocations, but I am also hoping that there is no noticeable overhead introduced. Let me know!

**Comment by ralfstx** [comment]
I had a look at your implementation. I like the idea of a `ParserContext` to provide state info like line, column, etc. What I don't like is the `ElementReader` to extend `JsonValue` - actually, it's *not* a JsonValue but a class related to parsing. I think ideally, the `JsonValue` types should not expose API related to parsing.

I've also rebased my draft and pushed it to the branch prototype-streaming. I'm not yet happy with this version, but I thought I'd share it for discussion.

What I did is, I introduced a JsonHandler interface that would process every parsing event. This allowed me to decouple the parser completely from the `JsonValue` types, so you could use it to build a custom data structure - [here's an example](https://github.com/ralfstx/minimal-json/blob/prototype-streaming/com.eclipsesource.json/src/test/java/com/eclipsesource/json/ParserHandlerExample.java). However, this interface is not typesafe and it doesn't look very clean and understandable so far. It's really just a start.

I'm also thinking about having a separate reader/handler for every nested array/object, so that an implementation can return domain-specific handlers at every level (such as the one for bus routes). On the other hand I'd like to avoid creating separate wrapper objects when reading JsonValues in order to keep the default mode fast...

**Comment by sbandara** [comment]
Hi Ralf,

thanks for evaluating, and for posting your own draft. You installed many more hooks, even for literals. That may be even better at limiting memory footprint. I had thought the main reason for using a streaming API would be extremely / infinitely long collections, and possibly those would be only at one or a few specific levels - hence "hybrid" and use default minimal-json behavior and representations at all other levels. 

> What I don't like is the ElementReader to extend JsonValue - actually, it's not a JsonValue but a class related to parsing. I think ideally, the JsonValue types should not expose API related to parsing.

Yes. The meaning of those two classes `ElementReader` and `MemberReader` is a little "fuzzy", maybe because they fulfill two roles in one and thus perhaps should have been separated: (1) they can take a "builder" (not parser/reader) role, and (2) they can be mixed into your default tree of JSON values (which is why they needed to be JSON values).

Note though that parser access is strictly limited by `addElement` and `addMember` being `protected` and thus not visible as members when default `JsonArray`s and `JsonObject`s are used, or when custom parser extensions are kept in their own package. Only those methods and factory requests get access to the parser state and could invoke skipping.

> However, this interface is not typesafe...

I had run into the same problem. Your `handleObjectStart` and `handleArrayStart` return `Object`, but perhaps you want to identify them as element and member collections, respectively. I tried so by making `JsonArray` and `JsonObject` implement the interfaces `ElementReader` and `MemberReader`, but this would have made `addElement` and `addMember` public. Therefore, I turned `ElementReader` and `MemberReader` into abstract classes and in consequence those had to inherit from `JsonValue` because `JsonArray` and `JsonObject` had to inherit from both.

I think fixing this and separating builders from mix-ins are related, and would love to give it a spin. I could also pull in your fine-grained hooks if welcome, by Saturday or so, but if you rather want to work on it on your own, let me know. I give you write access to my draft, just in case.

Best wishes,
Sam

**Comment by sbandara** [comment]
> What I don't like is the ElementReader to extend JsonValue - actually, it's not a JsonValue but a class related to parsing. I think ideally, the JsonValue types should not expose API related to parsing.

After some more thought and experimentation I was wondering if you could clarify whether you (a) object to mixing in custom representations in general, if you (b) would have liked to see the decision whether to include, skip, etc... fully separated from the tree of JsonValues, or if you (c) specifically take issue where `ElementReader` and `MemberReader` take a non-data, builder role as in the editor example. In other words, do you mean by "not a JsonValue" not strictly a representation of Json, or more generally not even a representation of values / data? 

Regarding (a), I see a benefit of mixing because it allows users to fully rely on minimal-json *except* where needed (e.g. for that one particularly long root array). To be more strict, we could allow custom collections to be parent of minimal-json `JsonValue`s but not vice-versa. That would relax constraints in other places, for example when using `write` on a `JsonValue` that is part of a hybrid structure (currently, a default implementation of `write` handles this, but I could happily remove it then).

To address (b), `addElement` and `addMember` could move into the factory / handler, but it would increase the burden on users. Currently, they can return a standard `JsonArray` and be done with it. They can also return a domain-specific or filtering representation. In both cases, no wrappers and no duplication of handler logic, and I find that to be extremely convenient. Of course we could still add `push` and `pop` of handlers.

For (c), we could define that returning `null` for the root collection transfers ownership of the data representation to the handler / factory. This would mean that `addElement` and `addMember` should move into the factory, see (b). Alternatively, we could allow two types of factory / handler, one that is more of just a factory as in my branch, and the other more of a handler that also relieves the parser from holding the tree. Both would be consistent with "strict mixing" as described in (a). The factory by the way can be an incomplete implementation of the handler.

Anyways, looking forward to hear what you think...

**Comment by sbandara** [comment]
I managed to merge your draft into mine, leaving only a few scars in JavaDocs and the test cases (editor case not yet adapted to recommended usage), but all pass. Could fix if this is going in the right direction.

As an experimental and easily revertible detail, this draft requires the handler methods to return `JsonValue` objects, but can also return `null`. `null` returned from a collection factory method (`handleArrayStart` or `handleObjectStart` no longer instructs the parser to skip the collection). Instead, `null` only relieves the parser of its responsibility to hold the tree.

The `CollectionFactory` as a specialization of `JsonHandler` could now be easily removed. I am wondering if the `DefaultJsonHandler` should be public though.

**Comment by ralfstx** [comment]
Hi Sam,

I'm still in the phase of collecting ideas for the streaming API. Maybe we should first collect and discuss different use cases. I've added a comment in https://github.com/ralfstx/minimal-json/issues/17#issuecomment-109580767.

As for the concerns I expressed about `ElementReader` and `MemberReader`, they are mostly about [single responsibility](https://en.wikipedia.org/wiki/Single_responsibility_principle): an object that is responsible for "reading an element" shouldn't represent a value at the same time. Likewise, a JsonArray is not a reader by its nature. A method `createElementReader` doesn't make sense in the context of a data structure returned by the parser or created programmatically.

Moreover, I wonder if the name is a good choice, because "reading" is already the responsibility of the parser. The `ElementReader` is there for doing something with the data that has been read, isn't it?

**Comment by ralfstx** [comment]
BTW, I can hardly import your changes because c8df13f0c1edf79196e0a37279ce1036efe3d39c breaks my IDE.

**Comment by sbandara** [comment]
Yes, they are misnomers and I changed them yesterday to names more in line with abstract arrays and objects. I also matched the naming of the factory methods to your handler interface. With your interface merged, the pattern in question could be removed easily. Sorry about removing those configuration files, I am still new to git. Is there a way for me to fix it or could you work around it? I saw your post on use cases, and I think we nail them already. But I'll take break from this then, and maybe you'll find some of it useful...

**Comment by ralfstx** [comment]
@sbandara I've eventually pushed a first version of the streaming API to master (c2217cdf). It's different from my first approach and also different from yours, but I picked up ideas from the discussion.

This version is pretty simple and does not add too much overhead, still I think it allows for simple solutions for all the use cases we've discussed: tracking positions of the input elements, omitting parts of the input, and building custom data structures.

The parser now issues events to a `JsonHandler` which then processes these events and creates whatever data model. On `startArray` and `startObject`, the handler can return an object that handles further events for this array / object. This would allow for your `ElementReader` and `MemberReader`.

Thanks for the discussion, that was really helpful. I hope you're not too disappointed that I didn't accept your pull request. I want to keep minimal-json as small and simple as possible, and I wanted to avoid to tie `JsonObject` and `JsonArray` to a parser-related type.

I hope you like this version. If there's anything you think should be improved before it's released, I'm interested to learn about it.

**Comment by sbandara** [comment]
Hi Ralf, Great to hear you found time to do it. This is a big deal. I'm sure your streaming API will make minimal-json attract entire communities of new people. I had a lot of fun prototyping and discussing designs with you. Keep up the awesome work! Sam

**Pull request closed without merging**
